### PR TITLE
Scroll Depth support

### PR DESCRIPTION
**Pull request by rdmurphy**
This pull adds support for the [Scroll Depth jQuery plugin](http://scrolldepth.parsnip.io), which is in use on [The Texas Tribune](https://www.texastribune.org). (Ignore the non-ideal branch name, this had other goals early on, heh).

For the most part, this mirrors the other depth tracker, but makes it support what Scroll Depth submits to GA.

### CODE REVIEW

**Comment by hampelm** [comment]
@rdmurphy Sweet! If you have a second, can you add a note (maybe in the deploy section of the readme) about running in Docker? Even that it's experimental and how it usually breaks (eg the db gets cleared every time the container stops)

**Comment by hampelm** [comment]
@rdmurphy If you have a second, can you rebase this onto master (or merge in master) and retry the PR? I'm happy to reconcile it too if you're booked the next couple days.

**Comment by rdmurphy** [comment]
@hampelm Done! Pretty sure it shook out properly. The only thing I'd maybe double check is the `autodiscover_stories()` function in `analytics.py`. That new? If so, it's still in there, I just don't remember it. 😬

**Comment by hampelm** [comment]
Thanks! I cut `autodiscover_stories` in an earlier PR, not sure why it's remerged. I can clear it up.

**Pull request merged**
